### ISSUE TITLE
How can I upload a new language pack ?

### ISSUE THREAD

**Issue by ben-s** [GetPublii/Publii-ui-locales#1]
Here is the french version (I don't know how to send this pack)
[fr.zip](https://github.com/GetPublii/Publii-ui-locales/files/8274151/fr.zip)

**Comment by GetPublii** [comment]
> Here is the french version (I don't know how to send this pack)
Thanks for the package, it was added a moment ago.

**Comment by ben-s** [comment]
Here is an updated version of french files.
A fex mistakes and missing labels. This version is much more natural.
I still need to check if some other labels are missing but I did not find any bugs for now.

[fr.zip](https://github.com/GetPublii/Publii-ui-locales/files/8292910/fr.zip)


Please, note that I cannot add my own .zip file from the Language settings. I always have a error message.
But If a put my unzipped files in the default languages directory, the theme is working.

I tried to zip my files from windows or 7z but it is always refused by the application language settings.

**Comment by pagelab** [comment]
> Please, note that I cannot add my own .zip file from the Language settings. I always have a error message.

@ben-s There were some tab characters in `config.json`. Tabs are invalid inside JSON. I removed them in the following version:  [fr.zip](https://github.com/GetPublii/Publii-ui-locales/files/8298510/fr.zip)

Now you can properly import the zip file in language settings.

**Comment by bobmitro** [comment]
@ben-s Could you "adjust" the phrazes "Preview your changes" and "Sync your website" to fit them on one line of text, maybe some shortcuts like "Sync site" etc...

**Comment by ben-s** [comment]
Here the 1.3 version.
There was 4 menu labels missing.
I shortened the rendering and Sync buttons label :
![image](https://user-images.githubusercontent.com/606174/158947717-11142bc4-24ff-449b-bafa-53772462432e.png)
[fr.zip](https://github.com/GetPublii/Publii-ui-locales/files/8302048/fr.zip)

**Comment by bobmitro** [comment]
Fantastic, thanks.

**Comment by rbenitezpagan** [comment]
@dziudek This can be closed.
