### ISSUE TITLE
Additional key naming and English translation errors

### ISSUE THREAD

**Issue by rbenitezpagan** [GetPublii/Publii-ui-locales#10]
# Additional key naming errors
## Typos
- [x] `errorOccured` > `errorOccurred`
- [x] `deletBackupsConfirmMsg` > `deleteBackupsConfirmMsg`
- [x] `deletBackupsErrorMsg` > `deleteBackupsErrorMsg`
- [x] `deletBackupsSuccessMsg` > `deleteBackupsSuccessMsg`
- [x] `selectedFileExsistsMsg` > `selectedFileExistsMsg`
- [x] `menuIemsRemoveMessage` > `menuItemsRemoveMessage`
- [x] `errorDuringPreviewCreatinMsg` > `errorDuringPreviewCreatingMsg`
- [x] `twitteSummaryCard` > `twitterSummaryCard`
- [x] `twitteSummaryCardLargeImage` > `twitterSummaryCardLargeImage`
- [x] `syncFTPNoPassowrdMsg` > `syncFTPNoPasswordMsg`
- [x] `testConnectionNoPassowrdMsg` > `testConnectionNoPasswordMsg`
- [x] `tagWillNotAppearInGgeneratedTagLists` > `tagWillNotAppearInGeneratedTagLists`
- [x] `processingRegenerateThumbanilsInfo` > `processingRegenerateThumbnailsInfo`
- [x] `addTagsToContentAutomaticallty` > `addTagsToContentAutomatically`
- [x] `configureThemeBeforeGenaratingPreview` > `configureThemeBeforeGeneratingPreview`
- [x] `ifCanonicalURLIsSetMmetaRobotsTagiInored` > `ifCanonicalURLIsSetMetaRobotsTagIgnored`

## Optional changes - keep camelCase
- [x] `usewideScrollbars` > `useWideScrollbars`
- [x] `sftpkeyNote` > `sftpKeyNote`
- [x] `reportBugInSupportdesk` > `reportBugInSupportDesk`

# English content translation error
- [x] Occurred - `"pluginSettingsLoadError": "An error occured during loading of plugin settings",` > `"pluginSettingsLoadError": "An error occurred during loading of plugin settings",`
- [x] Occurred - `"pluginSettingsSaveError": "An error occured during saving of plugin settings",` > `"pluginSettingsSaveError": "An error occurred during saving of plugin settings",`
- [x] Occurred - `"languageChangeError": "Language change error occured - please try again.",` > `"languageChangeError": "Language change error occurred - please try again.",`
- [x] Occurred - `"duplicatePostErrorMessage": "An error occured during duplication of the selected posts. Please try again.",` > `"duplicatePostErrorMessage": "An error occurred during duplication of the selected posts. Please try again.",`
- [x] Occurred - `"errorDuringPreviewCreatingMsg": "An error occured during preview creation.",` > `"errorDuringPreviewCreatingMsg": "An error occurred during preview creation.",`
- [x] Occurred - `"siteLoadingErrorMsg": "An error occured during loading of the selected website. Please check the website files and try again.",` > `"siteLoadingErrorMsg": "An error occurred during loading of the selected website. Please check the website files and try again.",`
- [x] Otherwise - `"apiRateLimitingNote": "Disable this option only if you are using Github Enterprise with disabled API rate limiting. Otherwhise disabling this option can cause deployment errors.",` > `"apiRateLimitingNote": "Disable this option only if you are using Github Enterprise with disabled API rate limiting. Otherwise disabling this option can cause deployment errors.",`
- [x] Publii - `"copyright": "Copyright 2022 <a href=\"https://tidycustoms.net\" target=\"_blank\" rel=\"noopener noreferrer\">TidyCustoms</a>. All rights reserved.<br>Publli is designed and maintained by core team with cooperation with <a href=\"https://github.com/dziudek\" target=\"_blank\" rel=\"noopener noreferrer\">Dev Zen</a> and is made possible by the <a href=\"https://electronjs.org\" target=\"_blank\" rel=\"noopener noreferrer\">Electron</a> Open Source project and other ",` > `"copyright": "Copyright 2022 <a href=\"https://tidycustoms.net\" target=\"_blank\" rel=\"noopener noreferrer\">TidyCustoms</a>. All rights reserved.<br>Publii is designed and maintained by core team with cooperation with <a href=\"https://github.com/dziudek\" target=\"_blank\" rel=\"noopener noreferrer\">Dev Zen</a> and is made possible by the <a href=\"https://electronjs.org\" target=\"_blank\" rel=\"noopener noreferrer\">Electron</a> Open Source project and other ",`
- [x] "support desk" - `"reportBugInSupportdesk": "Report a bug via our supportdesk",` > "reportBugInSupportDesk": "Report a bug via our support desk",

**Comment by dziudek** [comment]
@rbenitezpagan - thank you very much for your feedback - all fixes will be included in the upcoming v.0.40 of Publii :)

**Comment by rbenitezpagan** [comment]
@dziudek Probably `errorDuringPreviewCreatinMsg` can also be "creation" and not "creating" > `errorDuringPreviewCreationMsg`
