### ISSUE TITLE
Can I put the Chinese translation into Crowdin?

### ISSUE THREAD

**Issue by dyxang** [GetPublii/Publii-ui-locales#19]
This is a Chinese Translation：
[**v0.40 Chinese Simplified**](https://crowdin.com/project/publii-chinese-localization)

Pros:
- The translation of some words conforms to Chinese habits.
- The project is hosted to Crowdin, and everyone can participate in improving translation.

Cons:
- Translation level may be amateur.
- There may be translation errors.

**Comment by rbenitezpagan** [comment]
Hi @dyxang, 

Looks like you published to Crowdin already (based on your [link](https://crowdin.com/project/publii-chinese-localization)). Was the translation completed already? I tried accessing the files but I hit the LoginPage wall.

This seems to be a great idea for these kind of projects and perhaps the Publii Team could create an Open Source account ([Crowdin: Open-source project setup request form](https://crowdin.com/page/open-source-project-setup-request)), but so far it has been a GitHub community-driven effort to the best of my understanding.

There currently is a `v0.39.0` `zh-cn` version developed by @wtttb : https://github.com/GetPublii/Publii-ui-locales/issues/8

Something like this can help in the review process or you could work with @wtttb to review his current submission and use that as the base for the Crowdin work for future releases..

@GetPublii @dziudek This actually seems to be a good idea if there's an interest to have specific languages available without waiting for a community contributor.

Thanks!
Ramon Benitez-Pagan @rbenitezpagan

**Comment by wtttb** [comment]
> @dyxang We welcome and appreciate your submission, don't get me wrong. If you don't hear back from @wtttb next week, let's say July 20. We can go ahead and use your crowdin submission which is a better option to have multiple eyes on the language (given its complexity)'.
> 
> Additionally, let us know if you will be submitting the updates for `v0.40.0` so we can have both versions (39 and 40).
> 
> Thanks! Ramon Benitez-Pagan @rbenitezpagan

Hello, due to some special reasons, I cannot update the translation in time.
So later translations can use the version from @dyxang .
Hope you can update the README.
Other users can use the latest version in time. thank you very much!

**Comment by dyxang** [comment]
Thank  @wtttb for Publii 0.39.0 translation.
I have problem @rbenitezpagan,how to send this packs(Chinese Simplified and Traditional)?

- Pull request
- Upload zh.zip on this issue
- Leave my repo link

Thanks again!

**Comment by rbenitezpagan** [comment]
Thanks @wtttb for your submission. Community submissions are always welcome.

@dyxang Either of those options work really. Past examples have both submitted the zips and submitted PRs.

**Comment by rbenitezpagan** [comment]
@dziudek This can be closed.
