### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by gpsblues** [GetPublii/Publii-ui-locales#2]
Hi,

Here is the Italian version.

I noticed that deleting any additional language (it and also fr) does not show the translation. In its place comes "lang.removeLanguageMessage".

[it.zip](https://github.com/GetPublii/Publii-ui-locales/files/8325459/it.zip)

**Comment by bobmitro** [comment]
Hey @gpsblues

Thanks a lot for the Italian translation package.  The files were added to the oficial language repo.

**Comment by gpsblues** [comment]
Hi,
I encountered some issues (see images):

- The string "langs.removeLanguageMessage" is not displayed correctly

```
"removeLanguageMessage": "Do you really want to remove the language {languageName}?",
```

- Some "menu" strings have to be added manually

```
"unselectItem": "Deseleziona",
"insertActions": "Sposta la voce selezionata:",
"insertAfter": "Sposta qui sotto",
"insertBefore": "Sposta qui sopra",
"insertAsChild": "Inserisci come figlio"
```

- Some wysiwyg strings are not translated


![2022-04-04 15_39_15-Publii](https://user-images.githubusercontent.com/16633630/161558334-d690bb6e-9af6-4599-9c0b-b282685201f9.jpg)

![2022-04-04 15_43_07-Publii](https://user-images.githubusercontent.com/16633630/161558326-980db5b3-57d2-46a2-a1c7-f38e6a4b4cb2.jpg)

![2022-04-04 15_35_08-Publii](https://user-images.githubusercontent.com/16633630/161558330-75d962ce-de62-45b6-a8f2-2858844b9548.jpg)

**Comment by bobmitro** [comment]
Hey @gpsblues 

Can you update the Italian language files?

**Comment by gpsblues** [comment]
Hi Bob,

in this file I added the missing strings and improved something.
Ciao

[it 1.0.1.zip](https://github.com/GetPublii/Publii-ui-locales/files/8461964/it.1.0.1.zip)

**Comment by bobmitro** [comment]
@gpsblues Thanks a lot.

**Comment by gpsblues** [comment]
Thank you for Publii! :)
