### ISSUE TITLE
Ukrainian Localization

### ISSUE THREAD

**Issue by andrewnotea** [GetPublii/Publii-ui-locales#5]
Hi there
Here is the Ukrainian  Localization for Publii UI

❤️  🇺🇦

Locales for Simple and Persona.free themes — https://github.com/andrewnotea/Publii-Localization-Test/tree/main/Themes

[uk-ua.zip](https://github.com/GetPublii/Publii-ui-locales/files/8596482/uk-ua.zip)

**Comment by bobmitro** [comment]
Thanks a lot @andrewnotea 
Your translation has been added to the download section.

**Comment by rbenitezpagan** [comment]
@dziudek This can be closed.
