### ISSUE TITLE
Key naming error - translations.json

### ISSUE THREAD

**Issue by Cameo007** [GetPublii/Publii-ui-locales#7]
I found a naming error of the keys in translations.json.

The following keys in the "file" section musst be changed:
- renameBackupConfrimLabel
- renameBackupConfrimMsg
- restoreBackupConfrimLabel
- restoreBackupConfrimMsg

**Comment by rbenitezpagan** [comment]
Found another one.
`renderingProcessFiled` > `renderingProcessFailed`

**Comment by dziudek** [comment]
@Cameo007 @rbenitezpagan thank you for spotting this - it will be fixed in upcoming v.0.40 release :)
