### ISSUE TITLE
This is the Chinese simplified translation

### ISSUE THREAD

**Issue by wtttb** [GetPublii/Publii-ui-locales#8]
Full translation according to localized semantics
[zh-cn.zip](https://github.com/GetPublii/Publii-ui-locales/files/8838463/zh-cn.zip)
But for Chinese, There is some misplacement of text under the minimum window, example:
https://github.com/ChiefWang93/Publii-UI-Chinese-simplified

**Comment by fu-sen** [comment]
I'm working on a Japanese translation, but I ran into the same problem.
![スクリーンショット 2022-07-06 21 11 59](https://user-images.githubusercontent.com/5434159/177547349-64067e19-e7e1-4be1-87e4-1a9c5ee88178.png)

This can also be seen in the block editor.
![スクリーンショット 2022-07-06 21 12 09](https://user-images.githubusercontent.com/5434159/177547430-f5e93458-fa76-4fbe-93ee-5ab6fdaed8d4.png)

This problem will also occur in some other languages. (Korean will run into the same problem)
